<img src="../assets/ga-logo.png" style="float: left; margin: 20px; height: 55px">

# Hypothesis testing in action

---

### About
An introduction to hypothesis testing in action.

### Learning Objectives
- Define the key steps and terms in hypothesis testing.

### Notebook Guide
- Scenario
- Exploring the results
- Now You Try
- Conclusions and Takeaways

# Scenario

You’re an analyst for BIG Sodas, a producer of soft drinks.

They want to bring out a sugar-free version of their most popular lemonade drink, BIG Lemon.

They have two formulas they want to test: BIG Lemon Zero and Diet BIG Lemon.

They want you to help design an experiment to decide which of the two versions to produce.

The basic idea of the experiment is to do blind taste tests to see which flavour people prefer.

# Exploring the results

Let's open and explore the results of one of our blind taste tests.

The results are on this file:

https://raw.githubusercontent.com/juanatga/eda-experimental-design/main/data/sodas.csv

In [3]:
# Step 1: We want to see the file
import pandas as pd

file_path = "https://raw.githubusercontent.com/juanatga/eda-experimental-design/main/data/sodas.csv"

df = pd.read_csv(file_path)

In [4]:
# option 1: info

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   soda    400 non-null    str
 1   rating  400 non-null    int64
dtypes: int64(1), str(1)
memory usage: 6.4 KB

In [5]:
# option 2: Shape
df.shape

(400, 2)

In [6]:
# Advantage of shape - I can save the values
cols = df.shape[1]

rows = df.shape[0]

print("this dataset has",      
      rows, "and rows this many columns", cols)

this dataset has 400 and rows this many columns 2

In [7]:
df.head()

             soda  rating
0  diet_big_lemon       5
1  big_lemon_zero       8
2  big_lemon_zero       7
3  diet_big_lemon       5
4  big_lemon_zero       6

In [8]:
df.describe()

           rating
count  400.000000
mean     6.477500
std      1.445586
min      3.000000
25%      5.000000
50%      6.000000
75%      8.000000
max     10.000000

In [9]:
# I want to know how many unique values are and 
# how many 
# times each one of the is in the data set

# Use .value_count() to do that

df.value_counts()

soda            rating
big_lemon_zero  8         77
diet_big_lemon  5         73
big_lemon_zero  7         65
diet_big_lemon  6         64
big_lemon_zero  6         30
diet_big_lemon  4         29
                7         25
big_lemon_zero  9         23
diet_big_lemon  3          5
big_lemon_zero  10         4
diet_big_lemon  8          3
                9          1
big_lemon_zero  5          1
Name: count, dtype: int64

We have a data set of the two types of soda and the associated taste test rating.

Let's see the distribution of both the sodas and the ratings.

In [10]:
# I could iterate through the unique values

for product in df["soda"].unique():
  print(product)

diet_big_lemon
big_lemon_zero

In [11]:
# Option 2
# Use the values counts object, turn it into a df and plot it
summary = df.value_counts()

# check if this is a df
type(summary)

pandas.Series

What we're really interested in is the distribution of ratings *for each soda*.

In [27]:
# turn the summary series into a df (dont plot seris, thats messy)
# drom the first row of the summary series, we can see that the index is a
# multiindex, so we need to reset it to turn it into a df
vc_df = summary.reset_index()
vc_df.columns = ["soda", "rating", "count"]
vc_df.head()

             soda  rating  count
0  big_lemon_zero       8     77
1  diet_big_lemon       5     73
2  big_lemon_zero       7     65
3  diet_big_lemon       6     64
4  big_lemon_zero       6     30

In [32]:
import matplotlib

# plot the vc_df dataframe one group per soda unique values and one bar per
# rating value
# Use a supported non-interactive backend
matplotlib.use("Agg", force=True)

vc_df.plot.bar(
    x="soda",
    y="count",
    title="Soda Ratings",
    xlabel="Soda",
    ylabel="Count"
)

ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']

In [21]:
vc_df.head()

             soda  rating  count
0  big_lemon_zero       8     77
1  diet_big_lemon       5     73
2  big_lemon_zero       7     65
3  diet_big_lemon       6     64
4  big_lemon_zero       6     30

This tells us the "peak" of the distributions is different, with Diet BIG Lemon's average seemingly lower.

Let's verify this.

The average rating for Diet BIG Lemon does indeed seem lower.

Now it's time to test this statistically.

First of all, what are our hypotheses?

The null hypothesis is that **there is no difference** between the sodas.

$$
H_0: \mu_1 = \mu_2
$$

The alternate hypothesis is that **there *is* a difference** between the sodas.

$$
H_A: \mu_1 \ne \mu_2
$$

Now we need a statistical test for this scenario.

We'll use a two-sample t-test, which specifically tests **whether there is a significant difference between two sample means**.

In this case, it helps us answer: **do the ratings of these two sodas differ significantly?**

In [ ]:
# first, split the samples


# run a t-test to compare groups

To interpret the results, we use the p-value, which tells us **how likely we are to see this data assuming our null hypothesis is true**.

That is: how likely are we to see these ratings if the sodas are equally good?

If the p-value is low enough, we can **reject the null hypothesis** and say that the two sodas are not equal.

That is a tiny p-value, less that the typical threshold of 0.05.

This means **we reject the null hypothesis** and say that there **is** a difference between the sodas and that this difference is statistically significant.

# Now You Try!

We received some more test results, which we want to evaluate.

The new results are on this file:

https://raw.githubusercontent.com/juanatga/eda-experimental-design/main/data/sodas_2.csv


1. Read in `sodas_2.csv` as a `pandas DataFrame`.

2. What is the distribution of sodas?

3. What is the distribution of ratings? Calculate this for the entire dataset, and also for each soda separately.

Looks like the mean ratings for each soda are very close.

4. Run a two-sample t-test to see whether the sodas have similar ratings.

In [ ]:
# first, split the samples


# run a t-test to compare groups

The p-value is very high, around 0.75.

This means these results are very likely if the two sodas are similar.

We therefore **fail to reject the null hypothesis**.

# Conclusions and Takeaways

- Hypothesis tests require an experiment, data, and a statistical test
- If the p-value is below a certain threshold, usually 0.05, we *reject* the null hypothesis
- If the p-value is above this threshold, we *fail to reject* the null hypothesis